'use strict';

module.exports = {
  github: {
    owner: 'eggjs',
    repo: 'egg-feed-bot',
    token: process.env.github_token,
  },
  file: 'History.md',
  title: 'Egg Feed',
  cronType: 'monthly',
  repositories: [
    'eggjs/egg',
    'eggjs/egg-core',
    'eggjs/egg-cluster',
    'eggjs/egg-logger',
    'eggjs/egg-logrotator',
    'eggjs/egg-schedule',
    'eggjs/egg-onerror',
    'eggjs/egg-i18n',
    'eggjs/egg-jsonp',
    'eggjs/egg-watcher',
    'eggjs/egg-view',
    'eggjs/egg-session',
    'eggjs/egg-mock',
    'eggjs/egg-development',
    'eggjs/egg-multipart',
    'eggjs/egg-cookies',
    'eggjs/egg-session',

    'eggjs/egg-cli',
    'eggjs/egg-init',
    'eggjs/egg-bin',
    'eggjs/egg-scripts',
    'eggjs/doctools',

    'eggjs/egg-errors',
    'eggjs/egg-view-nunjucks',
    'eggjs/eslint-config-egg',
    'eggjs/egg-alinode',
    'eggjs/egg-mongoose',
    'eggjs/egg-sequelize',
    'eggjs/egg-mysql',
    'eggjs/egg-cors',
    'eggjs/egg-oss',
    'eggjs/egg-passport',
    'eggjs/egg-redis',
    'eggjs/egg-rest',
    'eggjs/egg-opentracing',
    'eggjs/egg-opentracing-zipkin',
    'eggjs/egg-ots',
  ],
};
